apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-summary
  description: Product Summary is an app for summarizing product information (such
    as name, price, and image) in other store blocks, such as the Shelf and the
    Minicart.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/product-summary
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: HCIH5RS1
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
